# Generated by Django 5.1 on 2025-07-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Harry Potter', max_length=50),
            preserve_default=False,
        ),
    ]
